"""Tests for GitHub PR opening on feature completion."""

import pytest
from unittest.mock import AsyncMock, MagicMock, patch

from agentharness.config import Config
from agentharness.dispatcher import _build_pr_body, _open_feature_pr
from agentharness.models import (
    FeatureState,
    FeatureStatus,
    PhaseInfo,
    PhaseStatus,
    TaskEntry,
    TaskStatus,
)


def _make_github_config() -> Config:
    cfg = MagicMock(spec=Config)
    cfg.storage_backend = "github"
    return cfg


def _make_azure_config() -> Config:
    cfg = MagicMock(spec=Config)
    cfg.storage_backend = "azure"
    return cfg


def _make_done_state(feature_id: str = "feat-20260427-abc") -> FeatureState:
    state = FeatureState(feature_id=feature_id, status=FeatureStatus.done)
    state = state.with_phase("analyzing", PhaseInfo(status=PhaseStatus.completed))
    state = state.with_phase("planning", PhaseInfo(status=PhaseStatus.completed))
    state = state.with_tasks_added([
        TaskEntry(
            task_id=f"{feature_id}-dev-task-a",
            phase="developing",
            status=TaskStatus.completed,
        ),
        TaskEntry(
            task_id=f"{feature_id}-dev-task-b",
            phase="developing",
            status=TaskStatus.completed,
        ),
    ])
    return state


class TestBuildPrBody:
    def test_includes_feature_id(self):
        state = _make_done_state("feat-20260427-xyz")
        body = _build_pr_body(state)
        assert "feat-20260427-xyz" in body

    def test_includes_phase_summary(self):
        state = _make_done_state("feat-phase-test")
        body = _build_pr_body(state)
        assert "**analyzing**" in body
        assert "completed" in body
        assert "**planning**" in body

    def test_includes_task_summary(self):
        state = _make_done_state("feat-task-test")
        body = _build_pr_body(state)
        assert "feat-task-test-dev-task-a" in body
        assert "feat-task-test-dev-task-b" in body
        assert "completed" in body

    def test_includes_tokens_section(self):
        state = _make_done_state()
        body = _build_pr_body(state)
        assert "### Tokens used" in body

    def test_tokens_unknown_when_no_usage(self):
        state = _make_done_state()
        body = _build_pr_body(state)
        assert "unknown" in body

    def test_includes_generated_by_footer(self):
        state = _make_done_state()
        body = _build_pr_body(state)
        assert "Generated by AgentHarness" in body


@pytest.mark.asyncio
class TestOpenFeaturePr:
    async def test_calls_create_pull_request_for_github_backend(self):
        state = _make_done_state("feat-pr-test")
        config = _make_github_config()

        mock_client = AsyncMock()
        mock_client.get_default_branch = AsyncMock(return_value="main")
        mock_client.create_pull_request = AsyncMock(return_value={"number": 42})
        mock_client.close = AsyncMock()

        with patch(
            "agentharness.github_client.GitHubClient",
            autospec=False,
        ) as MockGitHubClient:
            MockGitHubClient.from_config.return_value = mock_client
            await _open_feature_pr(state, config)

        MockGitHubClient.from_config.assert_called_once_with(config)
        mock_client.create_pull_request.assert_awaited_once()
        call_kwargs = mock_client.create_pull_request.call_args
        assert call_kwargs.kwargs["title"] == "feat-pr-test: implementation complete"
        assert call_kwargs.kwargs["head"] == "feat-pr-test"
        assert call_kwargs.kwargs["base"] == "main"

    async def test_pr_body_contains_feature_id(self):
        state = _make_done_state("feat-body-check")
        config = _make_github_config()

        mock_client = AsyncMock()
        mock_client.create_pull_request = AsyncMock(return_value={"number": 7})
        mock_client.close = AsyncMock()

        with patch("agentharness.github_client.GitHubClient") as MockGitHubClient:
            MockGitHubClient.from_config.return_value = mock_client
            await _open_feature_pr(state, config)

        body = mock_client.create_pull_request.call_args.kwargs["body"]
        assert "feat-body-check" in body

    async def test_no_op_for_azure_backend(self):
        state = _make_done_state("feat-azure")
        config = _make_azure_config()

        with patch("agentharness.github_client.GitHubClient") as MockGitHubClient:
            await _open_feature_pr(state, config)
            MockGitHubClient.from_config.assert_not_called()

    async def test_client_close_called_even_on_error(self):
        state = _make_done_state("feat-error")
        config = _make_github_config()

        mock_client = AsyncMock()
        mock_client.create_pull_request = AsyncMock(side_effect=RuntimeError("API down"))
        mock_client.close = AsyncMock()

        with patch("agentharness.github_client.GitHubClient") as MockGitHubClient:
            MockGitHubClient.from_config.return_value = mock_client
            # Should not raise — errors are logged, not propagated
            await _open_feature_pr(state, config)

        mock_client.close.assert_awaited_once()

    async def test_logs_pr_number_on_success(self, caplog):
        import logging
        state = _make_done_state("feat-log-test")
        config = _make_github_config()

        mock_client = AsyncMock()
        mock_client.create_pull_request = AsyncMock(return_value={"number": 99})
        mock_client.close = AsyncMock()

        with patch("agentharness.github_client.GitHubClient") as MockGitHubClient:
            MockGitHubClient.from_config.return_value = mock_client
            with caplog.at_level(logging.INFO, logger="agentharness.dispatcher"):
                await _open_feature_pr(state, config)

        assert "99" in caplog.text
        assert "feat-log-test" in caplog.text
