"""Tests for backend-aware init: _write_env, _detect_azure_env, and init_project backend selection."""

from __future__ import annotations

import json
import os
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest
from click.testing import CliRunner

from agentharness.cli import _detect_azure_env, _read_env_file, _write_env, main


# ---------------------------------------------------------------------------
# _detect_azure_env
# ---------------------------------------------------------------------------


def test_detect_azure_env_returns_connection_string_from_environment() -> None:
    with patch.dict(os.environ, {"AZURE_STORAGE_CONNECTION_STRING": "DefaultEndpointsProtocol=https;test"}):
        result = _detect_azure_env()
    assert result == {"AZURE_STORAGE_CONNECTION_STRING": "DefaultEndpointsProtocol=https;test"}


def test_detect_azure_env_returns_empty_when_not_set() -> None:
    env = {k: v for k, v in os.environ.items() if k != "AZURE_STORAGE_CONNECTION_STRING"}
    with patch.dict(os.environ, env, clear=True):
        result = _detect_azure_env()
    assert result == {}


# ---------------------------------------------------------------------------
# _write_env — azure backend
# ---------------------------------------------------------------------------


def test_write_env_azure_creates_env_with_connection_string(tmp_path: Path) -> None:
    with patch("agentharness.cli._detect_azure_env", return_value={"AZURE_STORAGE_CONNECTION_STRING": "conn-str-val"}):
        _write_env(tmp_path, backend="azure", force=False)

    env_file = tmp_path / ".env"
    assert env_file.exists()
    content = env_file.read_text()
    assert "AZURE_STORAGE_CONNECTION_STRING=conn-str-val" in content
    assert "GITHUB_TOKEN" not in content


def test_write_env_azure_prompts_when_connection_string_missing(tmp_path: Path) -> None:
    with patch("agentharness.cli._detect_azure_env", return_value={}):
        with patch("click.prompt", return_value="entered-conn-str") as mock_prompt:
            _write_env(tmp_path, backend="azure", force=False)

    mock_prompt.assert_called_once()
    call_kwargs = mock_prompt.call_args
    assert call_kwargs.kwargs.get("hide_input") is True

    env_file = tmp_path / ".env"
    assert "AZURE_STORAGE_CONNECTION_STRING=entered-conn-str" in env_file.read_text()


def test_write_env_azure_skips_when_already_present(tmp_path: Path) -> None:
    env_file = tmp_path / ".env"
    env_file.write_text("# Generated by agentharness init\nAZURE_STORAGE_CONNECTION_STRING=existing\n")

    with patch("agentharness.cli._detect_azure_env", return_value={}) as mock_detect:
        with patch("click.prompt") as mock_prompt:
            _write_env(tmp_path, backend="azure", force=False)

    mock_prompt.assert_not_called()
    assert "AZURE_STORAGE_CONNECTION_STRING=existing" in env_file.read_text()


def test_write_env_azure_force_overwrites_existing(tmp_path: Path) -> None:
    env_file = tmp_path / ".env"
    env_file.write_text("# Generated by agentharness init\nAZURE_STORAGE_CONNECTION_STRING=old-value\n")

    with patch("agentharness.cli._detect_azure_env", return_value={"AZURE_STORAGE_CONNECTION_STRING": "new-value"}):
        _write_env(tmp_path, backend="azure", force=True)

    assert "AZURE_STORAGE_CONNECTION_STRING=new-value" in env_file.read_text()


def test_write_env_azure_preserves_user_content_before_harness_section(tmp_path: Path) -> None:
    env_file = tmp_path / ".env"
    env_file.write_text("USER_KEY=user-value\n# Generated by agentharness init\nAZURE_STORAGE_CONNECTION_STRING=old\n")

    with patch("agentharness.cli._detect_azure_env", return_value={"AZURE_STORAGE_CONNECTION_STRING": "new-conn"}):
        _write_env(tmp_path, backend="azure", force=True)

    content = env_file.read_text()
    assert "USER_KEY=user-value" in content
    assert "AZURE_STORAGE_CONNECTION_STRING=new-conn" in content


# ---------------------------------------------------------------------------
# _write_env — github backend (regression: existing behavior preserved)
# ---------------------------------------------------------------------------


def test_write_env_github_creates_env_with_github_keys(tmp_path: Path) -> None:
    detected = {"GITHUB_TOKEN": "ghp_token123", "GITHUB_OWNER": "acme", "GITHUB_RUNS_REPO": "myrepo"}
    with patch("agentharness.cli._detect_github_env", return_value=detected):
        _write_env(tmp_path, backend="github", force=False)

    env_file = tmp_path / ".env"
    content = env_file.read_text()
    assert "GITHUB_TOKEN=ghp_token123" in content
    assert "GITHUB_OWNER=acme" in content
    assert "GITHUB_RUNS_REPO=myrepo" in content
    assert "AZURE_STORAGE_CONNECTION_STRING" not in content


def test_write_env_github_does_not_call_detect_azure_env(tmp_path: Path) -> None:
    with patch("agentharness.cli._detect_github_env", return_value={"GITHUB_TOKEN": "tok"}):
        with patch("agentharness.cli._detect_azure_env") as mock_azure_detect:
            with patch("click.prompt", return_value=""):
                _write_env(tmp_path, backend="github", force=False)

    mock_azure_detect.assert_not_called()


# ---------------------------------------------------------------------------
# init_project — backend selection updates .pipeline/config.json
# ---------------------------------------------------------------------------


def test_init_project_updates_pipeline_config_to_azure(tmp_path: Path) -> None:
    pipeline_dir = tmp_path / ".pipeline"
    pipeline_dir.mkdir()
    config_file = pipeline_dir / "config.json"
    config_file.write_text(json.dumps({"storage_backend": "github", "queues": {}}))

    runner = CliRunner()
    with patch("agentharness.cli._write_env"):
        with patch("click.prompt", return_value="azure"):
            result = runner.invoke(main, ["--config", str(config_file), "init", "--dir", str(tmp_path)])

    written = json.loads(config_file.read_text())
    assert written["storage_backend"] == "azure"
    assert written["queues"] == {}  # other fields preserved


def test_init_project_updates_pipeline_config_to_github(tmp_path: Path) -> None:
    pipeline_dir = tmp_path / ".pipeline"
    pipeline_dir.mkdir()
    config_file = pipeline_dir / "config.json"
    config_file.write_text(json.dumps({"storage_backend": "azure", "queues": {}}))

    runner = CliRunner()
    with patch("agentharness.cli._write_env"):
        with patch("click.prompt", return_value="github"):
            result = runner.invoke(main, ["--config", str(config_file), "init", "--dir", str(tmp_path)])

    written = json.loads(config_file.read_text())
    assert written["storage_backend"] == "github"


def test_init_project_defaults_to_existing_backend_in_config(tmp_path: Path) -> None:
    pipeline_dir = tmp_path / ".pipeline"
    pipeline_dir.mkdir()
    config_file = pipeline_dir / "config.json"
    config_file.write_text(json.dumps({"storage_backend": "github"}))

    prompts: list[str] = []

    def capture_prompt(text, **kwargs):
        prompts.append(text)
        return kwargs.get("default", "azure")

    runner = CliRunner()
    with patch("agentharness.cli._write_env"):
        with patch("click.prompt", side_effect=capture_prompt):
            runner.invoke(main, ["--config", str(config_file), "init", "--dir", str(tmp_path)])

    # The backend prompt should have defaulted to "github" (existing config value)
    backend_call = next((c for c in prompts if "backend" in c.lower() or "storage" in c.lower()), None)
    assert backend_call is not None


def test_init_project_defaults_to_azure_when_no_existing_config(tmp_path: Path) -> None:
    defaults: list[str] = []

    def capture_prompt(text, **kwargs):
        if "backend" in text.lower() or "storage" in text.lower():
            defaults.append(str(kwargs.get("default", "")))
        return kwargs.get("default", "azure")

    runner = CliRunner()
    with patch("agentharness.cli._write_env"):
        with patch("click.prompt", side_effect=capture_prompt):
            runner.invoke(main, ["init", "--dir", str(tmp_path)])

    assert "azure" in defaults


def test_init_project_passes_selected_backend_to_write_env(tmp_path: Path) -> None:
    pipeline_dir = tmp_path / ".pipeline"
    pipeline_dir.mkdir()
    config_file = pipeline_dir / "config.json"
    config_file.write_text(json.dumps({"storage_backend": "github"}))

    write_env_calls: list[tuple] = []

    def capture_write_env(target, backend, force):
        write_env_calls.append((target, backend, force))

    runner = CliRunner()
    with patch("agentharness.cli._write_env", side_effect=capture_write_env):
        with patch("click.prompt", return_value="azure"):
            runner.invoke(main, ["--config", str(config_file), "init", "--dir", str(tmp_path)])

    assert len(write_env_calls) == 1
    _, called_backend, _ = write_env_calls[0]
    assert called_backend == "azure"
