"""Click CLI entry points for AgentHarness."""

from __future__ import annotations

import json as _json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

import click
from rich.console import Console
from rich.table import Table
from rich import box

from agentharness.checkpoint import (
    init_checkpoint as _cp_init,
    load_checkpoint,
    update_phase as _cp_phase,
    update_task as _cp_task,
    set_tasks as _cp_set_tasks,
    query_next as _cp_query,
    list_checkpoints,
)

console = Console()


def _base_dir() -> Path:
    env = os.environ.get("AGENTHARNESS_BASE_DIR")
    return Path(env) if env else Path(".")


def _run_cmd(cmd: list[str], cwd: Path | None = None) -> str | None:
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=5, cwd=cwd)
        return r.stdout.strip() if r.returncode == 0 else None
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return None


def _gh_login_if_needed() -> str | None:
    token = _run_cmd(["gh", "auth", "token"])
    if token:
        return token
    gh_available = _run_cmd(["gh", "--version"]) is not None
    if not gh_available:
        return None
    console.print("[yellow]gh CLI is installed but not authenticated.[/yellow]")
    if click.confirm("Run gh auth login now?", default=True):
        subprocess.run(["gh", "auth", "login"], check=False)
        return _run_cmd(["gh", "auth", "token"])
    return None


def _detect_github_env(target: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    token = _gh_login_if_needed()
    if token:
        values["GITHUB_TOKEN"] = token
    remote_url = _run_cmd(["git", "remote", "get-url", "origin"], cwd=target)
    if remote_url:
        m = re.search(r"github\.com[:/]([^/]+)/([^/]+?)(?:\.git)?$", remote_url)
        if m:
            values["GITHUB_OWNER"] = m.group(1)
            values["GITHUB_RUNS_REPO"] = m.group(2)
    return values


def _read_env_file(env_file: Path) -> dict[str, str]:
    existing: dict[str, str] = {}
    if not env_file.exists():
        return existing
    for line in env_file.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, _, v = line.partition("=")
            existing[k.strip()] = v.strip()
    return existing


def _write_env(target: Path, force: bool) -> None:
    env_file = target / ".env"
    existing = _read_env_file(env_file)
    detected = _detect_github_env(target)
    KEYS = ["GITHUB_TOKEN", "GITHUB_OWNER", "GITHUB_RUNS_REPO"]
    missing = [k for k in KEYS if k not in existing]
    if not missing and not force:
        console.print("[dim]skip[/dim] .env (all values already present)")
        return
    keys_to_set = KEYS if force else missing
    console.print(f"\n[bold]Environment setup[/bold] ({'updating' if existing else 'creating'} .env)")
    new_values: dict[str, str] = {}
    for key in keys_to_set:
        if key in detected:
            new_values[key] = detected[key]
            display = detected[key][:8] + "…" if key == "GITHUB_TOKEN" else detected[key]
            console.print(f"  [dim]auto-detected[/dim] {key}={display}")
        else:
            value = click.prompt(key, default="", hide_input=key == "GITHUB_TOKEN", show_default=False, prompt_suffix=": ")
            new_values[key] = value
    raw = ""
    if env_file.exists():
        raw_lines = env_file.read_text().splitlines(keepends=True)
        harness_start = next(
            (i for i, l in enumerate(raw_lines) if l.strip() == "# Generated by agentharness init"),
            None,
        )
        raw = "".join(raw_lines[:harness_start] if harness_start is not None else raw_lines)
    all_harness = {**{k: existing[k] for k in KEYS if k in existing}, **new_values}
    harness_section = "# Generated by agentharness init\n" + "".join(
        f"{k}={v}\n" for k, v in all_harness.items() if v
    )
    separator = "\n" if raw and not raw.endswith("\n\n") else ""
    env_file.write_text(raw + separator + harness_section)
    action = "updated" if existing else "wrote"
    console.print(f"[green]{action}[/green] .env")


@click.group()
def main() -> None:
    """AgentHarness — autonomous agentic development pipeline."""


@main.command()
def brainstorm() -> None:
    """Start an interactive brainstorm session to define a feature brief."""
    from agentharness.brainstorm import start_brainstorm
    start_brainstorm()


def _copy_dir(src: Path, dst: Path, target: Path, force: bool) -> None:
    if not src.exists():
        return
    dst.mkdir(parents=True, exist_ok=True)
    for src_file in src.iterdir():
        if not src_file.is_file():
            continue
        dst_file = dst / src_file.name
        if dst_file.exists() and not force:
            console.print(f"[dim]skip[/dim] {dst_file.relative_to(target)}")
            continue
        shutil.copy2(src_file, dst_file)
        console.print(f"[green]wrote[/green] {dst_file.relative_to(target)}")


@main.command("init")
@click.option("--dir", "target_dir", default=".", show_default=True, type=click.Path())
@click.option("--force", is_flag=True, help="Overwrite existing files")
def init_project(target_dir: str, force: bool) -> None:
    """Install agent definitions, skills, and pipeline config into a project directory.

    Files are copied into the target repo's standard locations and are meant to be
    committed to the consumer repo's source control.
    """
    data_root = Path(__file__).parent / "data"
    target = Path(target_dir).resolve()

    if not data_root.exists():
        console.print("[red]Data files not found in package — reinstall agentharness.[/red]")
        sys.exit(1)

    # (source dir, destination dir, is each entry a directory?)
    groups = [
        (data_root / "agents", target / ".agents", False),
        (data_root / "pipeline", target / ".pipeline", False),
        (data_root / "claude-agents", target / ".claude" / "agents", False),
        (data_root / "skills", target / ".claude" / "skills", True),
    ]

    for src_dir, dst_dir, entries_are_dirs in groups:
        if entries_are_dirs:
            if src_dir.exists():
                for entry in src_dir.iterdir():
                    if entry.is_dir():
                        _copy_dir(entry, dst_dir / entry.name, target, force)
        else:
            _copy_dir(src_dir, dst_dir, target, force)

    _write_env(target, force)
    console.print("\n[bold]Done.[/bold] Run [bold]/oneshot <issue-number>[/bold] in Claude Code to start the pipeline.")


@main.command()
@click.pass_context
def watch(ctx: click.Context) -> None:
    """Open real-time TUI monitoring all pipeline features."""
    from agentharness.tui import run_monitor
    run_monitor()


@main.command()
@click.argument("feature_id")
def status(feature_id: str) -> None:
    """Show the current status of a feature."""
    base = _base_dir()
    try:
        cp = load_checkpoint(feature_id, base_dir=base)
    except (FileNotFoundError, ValueError):
        console.print(f"[red]Feature not found:[/red] {feature_id}")
        sys.exit(1)

    console.print(f"\n[bold]Feature:[/bold] {cp.feature_id}")
    console.print(f"[bold]Issue:[/bold]   #{cp.issue_number}")
    console.print(f"[bold]Created:[/bold] {cp.created_at.strftime('%Y-%m-%d %H:%M:%S UTC')}")

    console.print("\n[bold]Phases:[/bold]")
    for phase, info in cp.phases.items():
        icon = {"completed": "[green]✓[/green]", "in_progress": "[yellow]▶[/yellow]",
                "pending": "[dim]○[/dim]", "failed": "[red]✗[/red]"}.get(info.status, "?")
        ts = f"  [dim]{info.updated_at.strftime('%H:%M:%S')}[/dim]" if info.updated_at else ""
        console.print(f"  {icon} {phase:<14} {info.status}{ts}")

    if cp.tasks:
        console.print("\n[bold]Tasks:[/bold]")
        table = Table(box=box.SIMPLE, show_header=True, header_style="bold")
        table.add_column("Task", style="cyan")
        table.add_column("Status")
        table.add_column("Rev")
        for t in cp.tasks:
            style = {"completed": "[green]", "failed": "[red]", "in_progress": "[yellow]"}.get(t.status, "[dim]")
            table.add_row(t.name, f"{style}{t.status}[/]", str(t.revision))
        console.print(table)


@main.command("list")
def list_features() -> None:
    """List all features in the pipeline."""
    checkpoints = list_checkpoints(base_dir=_base_dir())
    if not checkpoints:
        console.print("[dim]No features found.[/dim]")
        return
    table = Table(box=box.SIMPLE, show_header=True, header_style="bold")
    table.add_column("Feature", style="cyan")
    table.add_column("Issue")
    table.add_column("Phases")
    table.add_column("Tasks")
    table.add_column("Created")
    for cp in checkpoints:
        completed_phases = sum(1 for p in cp.phases.values() if p.status == "completed")
        completed_tasks = sum(1 for t in cp.tasks if t.status == "completed")
        table.add_row(
            cp.feature_id,
            f"#{cp.issue_number}",
            f"{completed_phases}/{len(cp.phases)}",
            f"{completed_tasks}/{len(cp.tasks)}" if cp.tasks else "—",
            cp.created_at.strftime("%Y-%m-%d %H:%M"),
        )
    console.print(table)


# Checkpoint subcommands

@main.group("checkpoint")
def checkpoint_group() -> None:
    """Manage pipeline checkpoint state."""


@checkpoint_group.command("init")
@click.argument("issue_number", type=int)
def checkpoint_init(issue_number: int) -> None:
    """Create state.json for issue (idempotent)."""
    _cp_init(issue_number, base_dir=_base_dir())
    console.print(f"[green]checkpoint init:[/green] feat-{issue_number}")


@checkpoint_group.command("phase")
@click.argument("feature_id")
@click.argument("phase")
@click.argument("status")
def checkpoint_phase(feature_id: str, phase: str, status: str) -> None:
    """Update a phase status in the checkpoint."""
    _cp_phase(feature_id, phase, status, base_dir=_base_dir())


@checkpoint_group.command("task")
@click.argument("feature_id")
@click.argument("task_name")
@click.argument("status")
@click.option("--revision", type=int, default=None)
def checkpoint_task(feature_id: str, task_name: str, status: str, revision: int | None) -> None:
    """Update a task status in the checkpoint."""
    _cp_task(feature_id, task_name, status, revision=revision, base_dir=_base_dir())


@checkpoint_group.command("tasks")
@click.argument("feature_id")
@click.argument("task_names")
def checkpoint_tasks(feature_id: str, task_names: str) -> None:
    """Populate task list (comma-separated names) after planning."""
    names = [n.strip() for n in task_names.split(",") if n.strip()]
    _cp_set_tasks(feature_id, names, base_dir=_base_dir())


@checkpoint_group.command("status")
@click.argument("feature_id")
def checkpoint_status(feature_id: str) -> None:
    """Print next pending phase or task as JSON."""
    result = _cp_query(feature_id, base_dir=_base_dir())
    click.echo(_json.dumps(result))
