"""Click CLI entry points for AgentHarness."""

from __future__ import annotations

import asyncio
import json
import os
import re
import subprocess
import sys
from pathlib import Path

import click
from rich.console import Console
from rich.table import Table
from rich import box

from agentharness.config import load_config
from agentharness.storage import create_state_manager
from agentharness.github_labels import EPIC_PAUSED
from agentharness.github_client import GitHubClient, GitHubApiError
from agentharness.brainstorm import enqueue_planner, _convert_raw_issue
from agentharness.github_state import slug_title

console = Console()


def _run_cmd(cmd: list[str], cwd: Path | None = None) -> str | None:
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=5, cwd=cwd)
        return r.stdout.strip() if r.returncode == 0 else None
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return None


def _gh_login_if_needed() -> str | None:
    """Return a GitHub token, offering to run gh auth login if not yet authenticated."""
    token = _run_cmd(["gh", "auth", "token"])
    if token:
        return token

    gh_available = _run_cmd(["gh", "--version"]) is not None
    if not gh_available:
        return None

    console.print("[yellow]gh CLI is installed but not authenticated.[/yellow]")
    if click.confirm("Run gh auth login now?", default=True):
        subprocess.run(["gh", "auth", "login"], check=False)
        return _run_cmd(["gh", "auth", "token"])

    return None


def _detect_azure_env() -> dict[str, str]:
    values: dict[str, str] = {}
    conn_str = os.environ.get("AZURE_STORAGE_CONNECTION_STRING", "")
    if conn_str:
        values["AZURE_STORAGE_CONNECTION_STRING"] = conn_str
    return values


def _detect_github_env(target: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    token = _gh_login_if_needed()
    if token:
        values["GITHUB_TOKEN"] = token
    remote_url = _run_cmd(["git", "remote", "get-url", "origin"], cwd=target)
    if remote_url:
        m = re.search(r"github\.com[:/]([^/]+)/([^/]+?)(?:\.git)?$", remote_url)
        if m:
            values["GITHUB_OWNER"] = m.group(1)
            values["GITHUB_RUNS_REPO"] = m.group(2)
    return values


def _read_env_file(env_file: Path) -> dict[str, str]:
    existing: dict[str, str] = {}
    if not env_file.exists():
        return existing
    for line in env_file.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, _, v = line.partition("=")
            existing[k.strip()] = v.strip()
    return existing


_SECRET_KEYS = {"GITHUB_TOKEN", "AZURE_STORAGE_CONNECTION_STRING"}
_BACKEND_KEYS: dict[str, list[str]] = {
    "azure": ["AZURE_STORAGE_CONNECTION_STRING"],
    "github": ["GITHUB_TOKEN", "GITHUB_OWNER", "GITHUB_RUNS_REPO"],
}


def _write_env(target: Path, backend: str, force: bool) -> None:
    env_file = target / ".env"
    existing = _read_env_file(env_file)
    detected = _detect_azure_env() if backend == "azure" else _detect_github_env(target)

    KEYS = _BACKEND_KEYS.get(backend, _BACKEND_KEYS["github"])
    missing = [k for k in KEYS if k not in existing]

    if not missing and not force:
        console.print(f"[dim]skip[/dim] .env (all values already present)")
        return

    keys_to_set = KEYS if force else missing
    console.print(f"\n[bold]Environment setup[/bold] ({'updating' if existing else 'creating'} .env)")

    new_values: dict[str, str] = {}
    for key in keys_to_set:
        if key in detected:
            new_values[key] = detected[key]
            display = detected[key][:8] + "…" if key in _SECRET_KEYS else detected[key]
            console.print(f"  [dim]auto-detected[/dim] {key}={display}")
        else:
            value = click.prompt(key, default="", hide_input=key in _SECRET_KEYS, show_default=False, prompt_suffix=": ")
            new_values[key] = value

    # Strip previous harness section, keep everything else intact
    raw = ""
    if env_file.exists():
        raw_lines = env_file.read_text().splitlines(keepends=True)
        harness_start = next(
            (i for i, l in enumerate(raw_lines) if l.strip() == "# Generated by agentharness init"),
            None,
        )
        raw = "".join(raw_lines[:harness_start] if harness_start is not None else raw_lines)

    all_harness = {**{k: existing[k] for k in KEYS if k in existing}, **new_values}
    harness_section = "# Generated by agentharness init\n" + "".join(
        f"{k}={v}\n" for k, v in all_harness.items() if v
    )
    separator = "\n" if raw and not raw.endswith("\n\n") else ""
    env_file.write_text(raw + separator + harness_section)
    action = "updated" if existing else "wrote"
    console.print(f"[green]{action}[/green] .env")


def _print_started(feature_id: str) -> None:
    """Print pipeline start confirmation."""
    console.print(f"[green]Pipeline started:[/green] {feature_id}")
    console.print(f"Monitor: [bold]agentharness watch[/bold]")


async def _implement_with_epic_check(feature_id: str, config) -> None:
    """Check if feature is an epic child with paused parent before enqueuing."""
    # GitHub backend only
    if config.storage_backend != "github":
        await enqueue_planner(feature_id, config)
        _print_started(feature_id)
        return

    state_mgr = create_state_manager(config)
    gh_client = GitHubClient.from_config(config)

    try:
        # Try to load existing state
        try:
            state = await state_mgr.get(feature_id)
        except KeyError:
            # Raw issue with no state yet — enqueue_planner handles preconditions
            await enqueue_planner(feature_id, config)
            _print_started(feature_id)
            return

        # Check if this is an epic child
        if state.epic_parent is not None:
            try:
                parent_issue = await gh_client.get_issue(state.epic_parent)
            except GitHubApiError as exc:
                console.print(f"[yellow]Warning:[/yellow] Could not check parent epic #{state.epic_parent}: {exc.message}")
                console.print("Proceeding anyway — run agentharness status to check epic state.")
                # Don't block — proceed to enqueue_planner
            else:
                parent_labels = [label["name"] for label in parent_issue.get("labels", [])]

                if EPIC_PAUSED in parent_labels:
                    console.print("[red]Epic is paused[/red] — a child feature has failed.")
                    console.print(f"Parent epic: #{state.epic_parent}")
                    console.print(
                        "To retry: fix the failing child's brief, remove the epic:paused label from "
                        f"#{state.epic_parent}, then re-run this command."
                    )
                    raise SystemExit(1)

        # Non-epic or parent is not paused — proceed
        await enqueue_planner(feature_id, config)
        _print_started(feature_id)

    finally:
        await gh_client.close()
        await state_mgr.close()


@click.group()
@click.option("--config", "config_path", default=None, type=click.Path(), help="Path to config.json")
@click.pass_context
def main(ctx: click.Context, config_path: str | None) -> None:
    """AgentHarness — autonomous agentic development pipeline."""
    ctx.ensure_object(dict)
    ctx.obj["config_path"] = Path(config_path) if config_path else None


@main.command()
@click.pass_context
def brainstorm(ctx: click.Context) -> None:
    """Start an interactive brainstorm session to define a feature brief."""
    config_path = ctx.obj.get("config_path")
    try:
        config = load_config(config_path) if config_path else None
    except FileNotFoundError:
        config = None  # Config not required until submission

    from agentharness.brainstorm import start_brainstorm
    start_brainstorm(config)


@main.command()
@click.argument("brief_file", type=click.Path(exists=True))
@click.pass_context
def submit(ctx: click.Context, brief_file: str) -> None:
    """Upload a brief file to Azure blob storage. Does not start the pipeline."""
    config = load_config(ctx.obj.get("config_path"))
    from agentharness.brainstorm import upload_brief_file
    feature_id = asyncio.run(upload_brief_file(Path(brief_file), config))
    console.print(f"[green]Brief uploaded:[/green] {feature_id}")
    console.print(f"Start pipeline: [bold]agentharness implement {feature_id}[/bold]")


@main.command()
@click.argument("feature_id")
@click.pass_context
def implement(ctx: click.Context, feature_id: str) -> None:
    """Start the pipeline for an uploaded feature brief."""
    config = load_config(ctx.obj.get("config_path"))
    asyncio.run(_implement_with_epic_check(feature_id, config))


@main.command("convert")
@click.argument("issue_number", type=int)
@click.pass_context
def convert(ctx: click.Context, issue_number: int) -> None:
    """Convert an existing GitHub issue into an AgentHarness feature (in-place).

    Detects epic sub-issue relationships automatically and creates branches accordingly.
    Equivalent to the /convertforagent skill but as a CLI command.
    """
    config = load_config(ctx.obj.get("config_path"))

    async def run() -> None:
        gh_client = GitHubClient.from_config(config)
        try:
            issue = await gh_client.get_issue(issue_number)
        except GitHubApiError as exc:
            console.print(f"[red]Error fetching issue #{issue_number}:[/red] {exc.message}")
            raise SystemExit(1) from exc
        finally:
            await gh_client.close()

        title = issue.get("title") or "untitled"
        feature_id = f"feat-{slug_title(title)}"
        console.print(f"[dim]Issue #{issue_number}:[/dim] {title}")
        console.print(f"[dim]Feature ID:[/dim] {feature_id}")
        await _convert_raw_issue(feature_id, config)
        console.print(f"[green]Converted:[/green] {feature_id}")
        console.print(f"Start pipeline: [bold]agentharness implement {feature_id}[/bold]")

    asyncio.run(run())


@main.command("observe")
@click.option("--auto", is_flag=True, help="Enable auto-mode: drain brainstormed features serially (one at a time).")
@click.pass_context
def observe(ctx: click.Context, auto: bool) -> None:
    """Single observer process: polls all queues, spawns a subprocess per task."""
    import subprocess
    config = load_config(ctx.obj.get("config_path"))
    exe = str(Path(sys.executable).parent / "agentharness")
    log_dir = Path("logs")
    log_dir.mkdir(exist_ok=True)
    log_file = log_dir / "observer.log"
    fh = open(log_file, "a")
    cmd = [exe, "_observe"]
    if auto:
        cmd.append("--auto")
    proc = subprocess.Popen(
        cmd,
        stdout=fh,
        stderr=fh,
        start_new_session=True,
    )
    console.print(f"[green]Observer started[/green] (pid {proc.pid}) → logs/observer.log")
    if auto:
        console.print("[dim]Auto-mode: ON — will drain brainstormed features serially.[/dim]")
    console.print("Monitor with: [bold]agentharness watch[/bold]")


@main.command("_observe")
@click.option("--auto", is_flag=True, hidden=True)
@click.pass_context
def _observe(ctx: click.Context, auto: bool) -> None:
    """Internal: run the observer loop (do not call directly)."""
    from agentharness import auto_mode
    from agentharness.observer import observe as _run_observe
    from agentharness.run_task import configure_logging
    configure_logging()
    config = load_config(ctx.obj.get("config_path"))
    if auto:
        auto_mode.enable()
    asyncio.run(_run_observe(config))


@main.command("run-task")
@click.argument("queue_name")
@click.pass_context
def run_task_cmd(ctx: click.Context, queue_name: str) -> None:
    """Internal: run one task (reads TaskMessage JSON from stdin). Used by observer."""
    import sys as _sys
    from agentharness.run_task import configure_logging, run_task
    configure_logging()
    task_json = _sys.stdin.read()
    config = load_config(ctx.obj.get("config_path"))
    asyncio.run(run_task(queue_name, task_json, config))


@main.command()
@click.option("--lines", "-n", default=50, show_default=True, help="Lines of history per file")
@click.pass_context
def logs(ctx: click.Context, lines: int) -> None:
    """Stream all active task logs to the terminal (plain text, copyable)."""
    import subprocess
    log_dir = Path("logs")
    if not log_dir.exists():
        console.print("[yellow]No logs directory found. Start the observer first.[/yellow]")
        return
    log_files = sorted(log_dir.rglob("*.log"), key=lambda p: p.stat().st_mtime, reverse=True)
    if not log_files:
        console.print("[yellow]No log files found yet.[/yellow]")
        return
    console.print(f"[dim]Tailing {len(log_files)} log file(s). Ctrl+C to exit.[/dim]\n")
    subprocess.run(["tail", f"-n{lines}", "-F", *[str(f) for f in log_files]])


@main.command()
@click.pass_context
def watch(ctx: click.Context) -> None:
    """Open real-time TUI monitoring all pipeline features."""
    config = load_config(ctx.obj.get("config_path"))
    from agentharness.tui import run_monitor
    run_monitor(config)


@main.command()
@click.argument("feature_id")
@click.pass_context
def status(ctx: click.Context, feature_id: str) -> None:
    """Show the current status of a feature."""
    config = load_config(ctx.obj.get("config_path"))
    asyncio.run(_show_status(feature_id, config))


@main.command("init")
@click.option("--dir", "target_dir", default=".", show_default=True, type=click.Path(), help="Project directory to initialise")
@click.option("--force", is_flag=True, help="Overwrite existing files")
@click.pass_context
def init_project(ctx: click.Context, target_dir: str, force: bool) -> None:
    """Copy agent definitions and pipeline config into a project directory."""
    import shutil
    data_root = Path(__file__).parent / "data"
    target = Path(target_dir).resolve()

    if not data_root.exists():
        console.print("[red]Data files not found in package — reinstall agentharness.[/red]")
        sys.exit(1)

    # Detect current backend from existing config (becomes the prompt default)
    existing_pipeline_config = target / ".pipeline" / "config.json"
    default_backend = "azure"
    if existing_pipeline_config.exists():
        try:
            default_backend = json.loads(existing_pipeline_config.read_text()).get("storage_backend", "azure")
        except Exception:
            pass

    console.print("\n[bold]Backend selection[/bold]")
    console.print("  azure  — Azure Blob Storage + Azure Storage Queues (requires AZURE_STORAGE_CONNECTION_STRING)")
    console.print("  github — GitHub Issues + branches (requires GITHUB_TOKEN, auto-detects owner/repo)")
    backend = click.prompt(
        "Storage backend",
        type=click.Choice(["azure", "github"]),
        default=default_backend,
    )

    flat_destinations = [
        (data_root / "agents", target / ".agents"),
        (data_root / "pipeline", target / ".pipeline"),
    ]

    for src, dst in flat_destinations:
        if not src.exists():
            continue
        dst.mkdir(parents=True, exist_ok=True)
        for src_file in src.iterdir():
            dst_file = dst / src_file.name
            if dst_file.exists() and not force:
                console.print(f"[dim]skip[/dim] {dst_file.relative_to(target)} (use --force to overwrite)")
                continue
            shutil.copy2(src_file, dst_file)
            console.print(f"[green]wrote[/green] {dst_file.relative_to(target)}")

    # Update storage_backend in .pipeline/config.json to match the selected backend
    pipeline_config_path = target / ".pipeline" / "config.json"
    if pipeline_config_path.exists():
        try:
            config_data = json.loads(pipeline_config_path.read_text())
            config_data["storage_backend"] = backend
            pipeline_config_path.write_text(json.dumps(config_data, indent=2) + "\n")
            console.print(f"[green]set[/green] storage_backend={backend} in .pipeline/config.json")
        except Exception as exc:
            console.print(f"[yellow]Warning:[/yellow] Could not update storage_backend in config.json: {exc}")

    skills_src = data_root / "skills"
    if skills_src.exists():
        backend_skill_name = "github-storage" if backend == "github" else "azure-storage"
        backend_skill_src = skills_src / backend_skill_name
        if not backend_skill_src.exists():
            backend_skill_src = skills_src / "azure-storage"

        for skill_dir in skills_src.iterdir():
            if not skill_dir.is_dir():
                continue
            if skill_dir.name in ("azure-storage", "github-storage") and skill_dir != backend_skill_src:
                continue
            dst_skill = target / ".claude" / "skills" / skill_dir.name
            dst_skill.mkdir(parents=True, exist_ok=True)
            for src_file in skill_dir.iterdir():
                dst_file = dst_skill / src_file.name
                if dst_file.exists() and not force:
                    console.print(f"[dim]skip[/dim] {dst_file.relative_to(target)} (use --force to overwrite)")
                    continue
                shutil.copy2(src_file, dst_file)
                console.print(f"[green]wrote[/green] {dst_file.relative_to(target)}")

    _write_env(target, backend, force)

    console.print("\n[bold]Done.[/bold] Run [bold]agentharness observe[/bold] to start the pipeline.")


@main.command("list")
@click.pass_context
def list_features(ctx: click.Context) -> None:
    """List all features in the pipeline."""
    config = load_config(ctx.obj.get("config_path"))
    asyncio.run(_list_features(config))


async def _show_status(feature_id: str, config) -> None:
    state_mgr = create_state_manager(config)
    try:
        state = await state_mgr.get(feature_id)
    except KeyError:
        console.print(f"[red]Feature not found:[/red] {feature_id}")
        sys.exit(1)

    console.print(f"\n[bold]Feature:[/bold] {state.feature_id}")
    console.print(f"[bold]Status:[/bold]  {_status_style(state.status)}")
    console.print(f"[bold]Created:[/bold] {_fmt_dt(state.created_at)}")
    console.print(f"[bold]Updated:[/bold] {_fmt_dt(state.updated_at)}")

    if state.phases:
        console.print("\n[bold]Phases:[/bold]")
        phase_order = ["planning", "architecting", "designing", "developing", "reviewing"]
        for phase in phase_order:
            info = state.phases.get(phase)
            if info:
                icon = {"completed": "[green]✓[/green]", "in_progress": "[yellow]▶[/yellow]", "pending": "[dim]○[/dim]", "failed": "[red]✗[/red]"}.get(info.status, "?")
                duration = ""
                if info.started_at and info.completed_at:
                    secs = int((info.completed_at - info.started_at).total_seconds())
                    duration = f"  [dim]({_fmt_duration(secs)})[/dim]"
                console.print(f"  {icon} {phase:<14} {info.status}{duration}")

    if state.tasks:
        console.print("\n[bold]Tasks:[/bold]")
        table = Table(box=box.SIMPLE, show_header=True, header_style="bold")
        table.add_column("Task ID", style="cyan")
        table.add_column("Status")
        table.add_column("Worker")
        table.add_column("Rev")
        for t in state.tasks:
            status_str = _task_status_style(t.status)
            table.add_row(t.task_id, status_str, t.worker_id or "—", str(t.revision))
        console.print(table)

    if state.config.current_revision_round > 0:
        console.print(
            f"\n[yellow]Revision round:[/yellow] {state.config.current_revision_round} / {state.config.max_revisions}"
        )


async def _list_features(config) -> None:
    state_mgr = create_state_manager(config)
    features = await state_mgr.list_features()

    table = Table(box=box.SIMPLE, show_header=True, header_style="bold")
    table.add_column("Feature ID", style="cyan")
    table.add_column("Status")
    table.add_column("Updated")

    for state in features:
        table.add_row(
            state.feature_id,
            _status_style(state.status),
            _fmt_dt(state.updated_at),
        )

    console.print(table)


def _status_style(status) -> str:
    styles = {
        "done": "[green]done[/green]",
        "failed": "[red]failed[/red]",
        "developing": "[yellow]developing[/yellow]",
        "reviewing": "[yellow]reviewing[/yellow]",
        "dev_revision": "[yellow]dev_revision[/yellow]",
        "planning": "[blue]planning[/blue]",
        "architecting": "[blue]architecting[/blue]",
        "designing": "[blue]designing[/blue]",
        "brainstorming": "[blue]brainstorming[/blue]",
        "brainstormed": "[cyan]brainstormed[/cyan]",
    }
    return styles.get(str(status), str(status))


def _task_status_style(status) -> str:
    styles = {
        "completed": "[green]completed[/green]",
        "failed": "[red]failed[/red]",
        "in_progress": "[yellow]in_progress[/yellow]",
        "queued": "[dim]queued[/dim]",
    }
    return styles.get(str(status), str(status))


def _fmt_dt(dt) -> str:
    if dt is None:
        return "—"
    return dt.strftime("%Y-%m-%d %H:%M:%S UTC")


def _fmt_duration(seconds: int) -> str:
    if seconds < 60:
        return f"{seconds}s"
    m, s = divmod(seconds, 60)
    return f"{m}m {s}s"
