"""Git feature-branch implementation of ArtifactStorage."""

from __future__ import annotations

import asyncio
import logging
import os
from pathlib import Path

from agentharness.config import Config

# Number of bytes beyond which content is treated as binary for writing
_BINARY_THRESHOLD = 0

# GitHub hard file-size limit in bytes
_GITHUB_FILE_SIZE_LIMIT = 100 * 1024 * 1024  # 100 MB

_EXCLUDE_PATTERNS = """
# Auto-generated by AgentHarness — do not edit
node_modules/
.venv/
venv/
__pycache__/
*.egg-info/
dist/
build/
.tox/
.mypy_cache/
.pytest_cache/
*.pyc
*.pyo
# .NET build artifacts
bin/
obj/
# Playwright / browser binaries
.playwright/
ms-playwright/
# Next.js / frontend build caches
.next/
.nuxt/
.output/
"""

log = logging.getLogger(__name__)


def _resolve_git_dir(repo_root: Path) -> Path:
    """Return the real .git directory, resolving worktree gitdir pointers."""
    git_path = repo_root / ".git"
    if git_path.is_file():
        content = git_path.read_text().strip()
        if content.startswith("gitdir: "):
            return Path(content[len("gitdir:"):].strip())
    return git_path


async def _unstage_oversized_files(clone_root: Path) -> None:
    """Unstage any staged files that exceed GitHub's 100 MB limit."""
    proc = await asyncio.create_subprocess_exec(
        "git", "diff", "--cached", "--name-only",
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.DEVNULL,
        cwd=clone_root,
    )
    stdout, _ = await proc.communicate()
    for rel_path in stdout.decode(errors="replace").splitlines():
        abs_path = clone_root / rel_path
        try:
            size = abs_path.stat().st_size
        except OSError:
            continue
        if size > _GITHUB_FILE_SIZE_LIMIT:
            log.warning(
                "Unstaging %s (%.1f MB) — exceeds GitHub 100 MB limit",
                rel_path, size / (1024 * 1024),
            )
            reset_proc = await asyncio.create_subprocess_exec(
                "git", "reset", "HEAD", "--", rel_path,
                cwd=clone_root,
                stdout=asyncio.subprocess.DEVNULL,
                stderr=asyncio.subprocess.DEVNULL,
            )
            await reset_proc.communicate()


async def _run_git(*args: str, cwd: Path | None = None) -> bytes:
    """Run a git command, returning stdout. Raise RuntimeError on non-zero exit."""
    proc = await asyncio.create_subprocess_exec(
        "git",
        *args,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
        cwd=cwd,
    )
    stdout, stderr = await proc.communicate()
    if proc.returncode != 0:
        err = stderr.decode(errors="replace").strip()
        out = stdout.decode(errors="replace").strip()
        raise RuntimeError(
            f"git {' '.join(args)} failed (exit {proc.returncode}): "
            f"{err or out}"
        )
    return stdout


class GitHubArtifactStore:
    """Artifact store backed by a git feature branch in a GitHub repository.

    Each feature gets an isolated clone at ``clone_dir/{feature_id}/``.
    """

    def __init__(
        self,
        owner: str,
        repo: str,
        feature_id: str,
        clone_dir: Path,
        base_branch: str | None = None,
    ) -> None:
        self._owner = owner
        self._repo = repo
        self._feature_id = feature_id
        self._clone_dir = clone_dir
        self._clone_root = clone_dir / feature_id
        self._base_branch = base_branch

    # ------------------------------------------------------------------
    # Factory
    # ------------------------------------------------------------------

    @classmethod
    def from_config(cls, config: Config, feature_id: str, base_branch: str | None = None) -> GitHubArtifactStore:
        owner = config.github.owner
        repo = config.github.runs_repo
        clone_dir = Path(config.github.clone_dir)
        return cls(owner=owner, repo=repo, feature_id=feature_id, clone_dir=clone_dir, base_branch=base_branch)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    async def _ensure_clone(self) -> None:
        """Clone the repo if a valid git clone does not exist at clone_root."""
        if not (self._clone_root / ".git").exists():
            if self._clone_root.exists():
                # Directory exists but has no .git — wipe and re-clone so git
                # operations don't fall back to the parent repo's .git.
                import shutil
                shutil.rmtree(self._clone_root)
            self._clone_root.parent.mkdir(parents=True, exist_ok=True)
            token = os.environ.get("GITHUB_TOKEN", "")
            clone_url = f"https://{token}@github.com/{self._owner}/{self._repo}.git"
            await _run_git("clone", clone_url, str(self._clone_root))

        exclude_file = _resolve_git_dir(self._clone_root) / "info" / "exclude"
        exclude_file.parent.mkdir(parents=True, exist_ok=True)
        try:
            existing = exclude_file.read_text()
        except OSError:
            existing = ""
        if "AgentHarness" not in existing:
            exclude_file.write_text(existing + _EXCLUDE_PATTERNS)

    # ------------------------------------------------------------------
    # ArtifactStorage protocol
    # ------------------------------------------------------------------

    async def _checkout_or_create(self, branch_name: str) -> None:
        """Checkout *branch_name* if it exists locally/remotely, else create it.

        Three-tier fallback:
        1. Checkout existing local branch (fast path).
        2. Create local tracking branch from remote (epic children 2..N where the
           branch already exists on remote but not locally).
        3. Create fresh local branch (brand-new branch, no remote copy yet).
        """
        try:
            await _run_git("-C", str(self._clone_root), "checkout", branch_name)
        except RuntimeError:
            try:
                # Branch exists on remote but not locally — create local tracking branch
                await _run_git(
                    "-C", str(self._clone_root),
                    "checkout", "-b", branch_name, f"origin/{branch_name}",
                )
            except RuntimeError:
                # Branch doesn't exist anywhere — create fresh local branch
                await _run_git("-C", str(self._clone_root), "checkout", "-b", branch_name)

    async def upload(self, path: str, content: str | bytes) -> None:
        """Write *content* to *path* on the feature branch and push."""
        await self._ensure_clone()

        # Bring remote refs up to date; tolerate a branch that doesn't exist
        # remotely yet (fetch may fail on first push for a brand-new branch).
        try:
            await _run_git(
                "-C", str(self._clone_root),
                "fetch", "origin", self._feature_id,
            )
        except RuntimeError:
            pass

        await self._checkout_or_create(self._feature_id)

        # Fast-forward local branch to match remote (another agent may have pushed
        # since this clone was initialised; tolerate missing remote branch).
        try:
            await _run_git(
                "-C", str(self._clone_root),
                "merge", "--ff-only", f"origin/{self._feature_id}",
            )
        except RuntimeError:
            pass

        # Write the file into the working tree.
        dest = self._clone_root / path
        dest.parent.mkdir(parents=True, exist_ok=True)
        if isinstance(content, str):
            dest.write_text(content, encoding="utf-8")
        else:
            dest.write_bytes(content)

        await _run_git("-C", str(self._clone_root), "add", "-f", path)

        # Commit only if there is something staged (nothing-to-commit is OK).
        try:
            await _run_git(
                "-C", str(self._clone_root),
                "commit", "-m", f"agent: upload {path}",
            )
        except RuntimeError as exc:
            msg = str(exc).lower()
            if "nothing to commit" not in msg and "no changes added to commit" not in msg:
                raise

        await _run_git(
            "-C", str(self._clone_root),
            "push", "origin", self._feature_id,
        )

    async def download(self, path: str) -> str:
        """Return the UTF-8 contents of *path* from the remote feature branch."""
        await self._ensure_clone()

        await _run_git(
            "-C", str(self._clone_root),
            "fetch", "origin", self._feature_id,
        )
        stdout = await _run_git(
            "-C", str(self._clone_root),
            "show", f"origin/{self._feature_id}:{path}",
        )
        return stdout.decode("utf-8")

    async def exists(self, path: str) -> bool:
        """Return True if *path* exists on the remote feature branch."""
        await self._ensure_clone()

        try:
            await _run_git(
                "-C", str(self._clone_root),
                "fetch", "origin", self._feature_id,
            )
            stdout = await _run_git(
                "-C", str(self._clone_root),
                "ls-tree", "-r", f"origin/{self._feature_id}", "--name-only",
            )
        except RuntimeError:
            return False

        listed_paths = stdout.decode("utf-8").splitlines()
        return path in listed_paths

    async def commit_workdir_changes(self, message: str) -> bool:
        """Stage all changes under the work dir, commit, and push to the feature branch.

        Returns True if a new commit was created, False if nothing was staged.
        """
        await self._ensure_clone()

        try:
            await _run_git("-C", str(self._clone_root), "fetch", "origin", self._feature_id)
        except RuntimeError:
            pass

        await _run_git("-C", str(self._clone_root), "checkout", self._feature_id)

        try:
            await _run_git(
                "-C", str(self._clone_root),
                "merge", "--ff-only", f"origin/{self._feature_id}",
            )
        except RuntimeError:
            pass

        await _run_git("-C", str(self._clone_root), "add", "-A")

        await _unstage_oversized_files(self._clone_root)

        try:
            await _run_git("-C", str(self._clone_root), "commit", "-m", message)
        except RuntimeError as exc:
            if "nothing to commit" in str(exc).lower():
                return False
            raise

        await _run_git("-C", str(self._clone_root), "push", "origin", self._feature_id)
        return True

    async def sync_working_branch(self) -> None:
        """Sync the working branch with remote before running an agent task.

        Fetches origin, fast-forwards the feature branch (falling back to
        -X ours on conflict), then merges the default base branch to reduce
        divergence from upstream. All conflict resolution prefers existing
        feature-branch content (-X ours).
        """
        await self._ensure_clone()

        try:
            await _run_git("-C", str(self._clone_root), "fetch", "origin")
        except RuntimeError as exc:
            log.warning("sync_working_branch: fetch failed, skipping sync: %s", exc)
            return

        await self._checkout_or_create(self._feature_id)

        try:
            await _run_git(
                "-C", str(self._clone_root),
                "merge", "--ff-only", f"origin/{self._feature_id}",
            )
        except RuntimeError:
            try:
                await _run_git(
                    "-C", str(self._clone_root),
                    "merge", "-X", "ours", "--no-edit", f"origin/{self._feature_id}",
                )
            except RuntimeError as exc:
                log.warning("sync_working_branch: cannot sync remote feature branch: %s", exc)

        if self._base_branch is not None:
            base = self._base_branch
        else:
            base = await self._get_default_branch()

        if not base or base == self._feature_id:
            return

        try:
            await _run_git(
                "-C", str(self._clone_root),
                "merge", "-X", "ours", "--no-edit", f"origin/{base}",
            )
            log.info(
                "sync_working_branch: merged origin/%s into %s",
                base, self._feature_id,
            )
        except RuntimeError as exc:
            log.warning("sync_working_branch: base branch merge failed: %s — aborting", exc)
            try:
                await _run_git("-C", str(self._clone_root), "merge", "--abort")
            except RuntimeError:
                pass

    async def _get_default_branch(self) -> str | None:
        """Return the default branch name from origin/HEAD, or None if unavailable."""
        try:
            stdout = await _run_git(
                "-C", str(self._clone_root),
                "symbolic-ref", "refs/remotes/origin/HEAD", "--short",
            )
            ref = stdout.decode().strip()
            return ref.removeprefix("origin/") if ref.startswith("origin/") else ref
        except RuntimeError:
            return None

    async def close(self) -> None:
        """No-op; git subprocesses are short-lived."""

    # ------------------------------------------------------------------
    # Extra helper (used by run_task.py for developer agent work dir)
    # ------------------------------------------------------------------

    def get_work_dir(self) -> Path:
        """Return the local directory where developer agents write code."""
        return self._clone_root
