"""Protocol types for pluggable storage backends (Azure, GitHub, etc.)."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Protocol

from agentharness.models import FeatureState, TaskMessage


@dataclass
class RawMessage:
    """Backend-agnostic message handle returned by receive_task."""

    id: str
    pop_receipt: str
    content: str
    dequeue_count: int = field(default=0)


class ArtifactStorage(Protocol):
    async def upload(self, path: str, content: str | bytes) -> None: ...
    async def download(self, path: str) -> str: ...
    async def exists(self, path: str) -> bool: ...
    async def close(self) -> None: ...
    def get_work_dir(self) -> Path | None: ...
    async def commit_workdir_changes(self, message: str) -> bool: ...


class TaskQueue(Protocol):
    async def send_task(self, task: TaskMessage, visibility_timeout: int = 0) -> None: ...
    async def receive_task(self, visibility_timeout: int = 30) -> tuple[TaskMessage, RawMessage] | None: ...
    async def delete_message(self, raw: RawMessage) -> None: ...
    async def extend_visibility(self, raw: RawMessage, timeout: int) -> RawMessage: ...
    async def move_to_dead_letter(self, raw: RawMessage, dead_letter_queue_name: str) -> None: ...
    async def purge(self) -> None: ...
    async def ensure_exists(self) -> None: ...
    async def get_depth(self) -> int: ...
    async def close(self) -> None: ...


class StateBackend(Protocol):
    async def create(self, state: FeatureState, brief_content: str = "") -> None: ...
    async def get(self, feature_id: str) -> FeatureState: ...
    async def update(
        self,
        feature_id: str,
        updater: Callable[[FeatureState], FeatureState],
    ) -> FeatureState: ...
    async def set_worktree_path(self, feature_id: str, worktree_path: str) -> None: ...
    async def set_cleanup_warning(self, feature_id: str, message: str) -> None: ...
    async def list_features(self) -> list[FeatureState]: ...
    async def open_review(self, feature_id: str) -> str | None: ...
    async def close(self) -> None: ...
